# Generated by Django 4.2.7 on 2024-02-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_image',
            field=models.ImageField(default='', upload_to='groups/'),
            preserve_default=False,
        ),
    ]
