# Generated by Django 4.2.7 on 2024-02-21 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_group_group_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='posts',
        ),
        migrations.CreateModel(
            name='Group_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='Group_post/')),
                ('context', models.TextField(max_length=3000, verbose_name='post text')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group_post',
                'verbose_name_plural': 'Group_posts',
                'ordering': ['data_created'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='group_post',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_group', to='social.group_post'),
        ),
    ]
