# Generated by Django 4.2.7 on 2024-02-24 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='PaymentStatus',
        ),
    ]
