# Generated by Django 4.2.7 on 2024-02-29 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
